"""Turn EXP-2026-09-002's recorded runs into its tables and metrics.

Reads ``data/runs.jsonl`` — the only source of truth for this experiment — and writes
``tables/per_run.md``, ``data/metrics.json``, and the YAML block to paste into
``manifest.yaml``. Nothing here is typed by hand into the write-up: the contract's rule is
that a number in the record traces to a recorded run, and a table transcribed by a human is
exactly where that trace breaks.

    uv run python -m utils.scripts.research.report_memory_callback
"""

from __future__ import annotations

import json
import statistics
from pathlib import Path

EXPERIMENT = (
    Path(__file__).resolve().parents[3]
    / "docs/research/experiments/EXP-2026-09-002-character-memory-callback-rerun"
)

#: Reported per arm. The primary first.
METRICS = [
    "verbatim_callback_rate",
    "verbatim_callback_rate_loose",
    "recall_fire_rate",
    "cue_share",
    "quote_offer_share",
    "memories_per_turn",
]


def load() -> list[dict]:
    path = EXPERIMENT / "data" / "runs.jsonl"
    rows = [json.loads(line) for line in path.read_text().splitlines() if line.strip()]
    # A run whose turns errored is not a measurement and must never be averaged into an arm
    # (EXP-2026-08-001's lesson). It stays in runs.jsonl — excluded, not deleted.
    return rows


def summarise(rows: list[dict]) -> dict:
    usable = [r for r in rows if not r.get("broken")]
    excluded = [r for r in rows if r.get("broken")]
    out: dict = {"excluded_runs": len(excluded), "arms": {}}
    for arm in ("off", "on"):
        arm_rows = [r for r in usable if r["arm"] == arm]
        values: dict = {}
        for metric in METRICS:
            present = [r[metric] for r in arm_rows if r.get(metric) is not None]
            if not present:
                values[metric] = None
                continue
            values[metric] = {
                "mean": round(statistics.fmean(present), 4),
                # With n = 2 this is the spread of two points, not an estimate of a
                # distribution. The write-up has to say so; the number alone cannot.
                "std": round(statistics.pstdev(present), 4) if len(present) > 1 else None,
                "n": len(present),
                "runs": present,
            }
        out["arms"][arm] = values
    return out


def table(rows: list[dict]) -> str:
    head = (
        "| arm | run | turns | beats | eligible | callbacks | rate | rate(loose) | "
        "recall turns | surfaced | cue share | quote offer | mem/turn | ok |\n"
    )
    head += "| " + " | ".join(["---"] * 14) + " |\n"
    body = ""
    for r in sorted(rows, key=lambda r: (r["arm"], r["run"])):
        body += (
            f"| {r['arm']} | {r['run']} | {r['turns']} | {r['character_beats']} | "
            f"{r['eligible_beats']} | {r['callbacks']} | {r['verbatim_callback_rate']} | "
            f"{r['verbatim_callback_rate_loose']} | {r['recall_turns']} | "
            f"{r['memories_surfaced']} | {r['cue_share']} | {r['quote_offer_share']} | "
            f"{r['memories_per_turn']} | {'yes' if not r.get('broken') else 'NO'} |\n"
        )
    return head + body


def main() -> int:
    rows = load()
    summary = summarise(rows)

    (EXPERIMENT / "tables").mkdir(parents=True, exist_ok=True)
    (EXPERIMENT / "tables" / "per_run.md").write_text(
        "<!-- generated by utils/scripts/research/report_memory_callback.py — do not edit -->\n\n"
        + table(rows)
    )
    (EXPERIMENT / "data" / "metrics.json").write_text(json.dumps(summary, indent=2) + "\n")

    print(table(rows))
    print("manifest metrics.values (paste):")
    for arm, values in summary["arms"].items():
        for metric, v in values.items():
            if v is None:
                continue
            std = "null" if v["std"] is None else v["std"]
            print(f"    {metric}_{arm}: {{mean: {v['mean']}, std: {std}, n: {v['n']}}}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
