"""baseline

Revision ID: b23834895e1c
Revises: 
Create Date: 2026-06-26 16:44:07.407673

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import Text
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b23834895e1c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_settings',
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('value', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('storylines',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('genre', sa.String(), nullable=False),
    sa.Column('tagline', sa.String(), nullable=True),
    sa.Column('premise', sa.Text(), nullable=True),
    sa.Column('world_primer', sa.Text(), nullable=True),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('symbol_color', sa.String(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('characters',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('storyline_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('color', sa.String(), nullable=False),
    sa.Column('mono', sa.String(), nullable=False),
    sa.Column('traits', sa.String(), nullable=False),
    sa.Column('speech', sa.String(), nullable=False),
    sa.Column('goal', sa.String(), nullable=False),
    sa.Column('secret', sa.String(), nullable=False),
    sa.Column('appearance', sa.Text(), nullable=True),
    sa.Column('background', sa.Text(), nullable=True),
    sa.Column('personality', sa.Text(), nullable=True),
    sa.Column('portrait', sa.String(), nullable=True),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['storyline_id'], ['storylines.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('characters', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_characters_storyline_id'), ['storyline_id'], unique=False)

    op.create_table('context_documents',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('storyline_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('include_draft', sa.Boolean(), nullable=False),
    sa.Column('include_rag', sa.Boolean(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('char_count', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['storyline_id'], ['storylines.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('context_documents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_context_documents_storyline_id'), ['storyline_id'], unique=False)

    op.create_table('graph_type_definitions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('storyline_id', sa.String(), nullable=True),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('type_name', sa.String(), nullable=False),
    sa.Column('field_schema', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('valence', sa.String(), nullable=True),
    sa.Column('decay', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['storyline_id'], ['storylines.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('storyline_id', 'kind', 'type_name', name='uq_graph_type_scope')
    )
    with op.batch_alter_table('graph_type_definitions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_graph_type_definitions_storyline_id'), ['storyline_id'], unique=False)

    op.create_table('scenarios',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('storyline_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('genre', sa.String(), nullable=False),
    sa.Column('tone', sa.String(), nullable=False),
    sa.Column('goal', sa.String(), nullable=False),
    sa.Column('setting_id', sa.String(), nullable=False),
    sa.Column('opening', sa.String(), nullable=False),
    sa.Column('cast_ids', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('branches', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['storyline_id'], ['storylines.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('scenarios', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_scenarios_setting_id'), ['setting_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_scenarios_storyline_id'), ['storyline_id'], unique=False)

    op.create_table('settings',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('storyline_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('desc', sa.String(), nullable=False),
    sa.Column('atmosphere', sa.Text(), nullable=True),
    sa.Column('features', sa.Text(), nullable=True),
    sa.Column('current_state', sa.Text(), nullable=True),
    sa.Column('image', sa.String(), nullable=True),
    sa.Column('timeline', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['storyline_id'], ['storylines.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('settings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_settings_storyline_id'), ['storyline_id'], unique=False)

    op.create_table('stat_definitions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('storyline_id', sa.String(), nullable=False),
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('min', sa.Integer(), nullable=False),
    sa.Column('max', sa.Integer(), nullable=False),
    sa.Column('default', sa.Integer(), nullable=False),
    sa.Column('visibility', sa.String(), nullable=False),
    sa.Column('guidance', sa.String(), nullable=True),
    sa.Column('applies_to', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('bands', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.ForeignKeyConstraint(['storyline_id'], ['storylines.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('storyline_id', 'key', name='uq_stat_def_storyline_key')
    )
    with op.batch_alter_table('stat_definitions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_stat_definitions_storyline_id'), ['storyline_id'], unique=False)

    op.create_table('character_stats',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('character_id', sa.String(), nullable=False),
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('value', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('character_id', 'key', name='uq_char_stat_character_key')
    )
    with op.batch_alter_table('character_stats', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_character_stats_character_id'), ['character_id'], unique=False)

    op.create_table('play_sessions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('scenario_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['scenario_id'], ['scenarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('play_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_play_sessions_scenario_id'), ['scenario_id'], unique=False)

    op.create_table('events',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('scenario_id', sa.String(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('visibility', sa.String(), nullable=False),
    sa.Column('data', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.ForeignKeyConstraint(['scenario_id'], ['scenarios.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['play_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_events_scenario_id'), ['scenario_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_events_session_id'), ['session_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_events_session_id'))
        batch_op.drop_index(batch_op.f('ix_events_scenario_id'))

    op.drop_table('events')
    with op.batch_alter_table('play_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_play_sessions_scenario_id'))

    op.drop_table('play_sessions')
    with op.batch_alter_table('character_stats', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_character_stats_character_id'))

    op.drop_table('character_stats')
    with op.batch_alter_table('stat_definitions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stat_definitions_storyline_id'))

    op.drop_table('stat_definitions')
    with op.batch_alter_table('settings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_settings_storyline_id'))

    op.drop_table('settings')
    with op.batch_alter_table('scenarios', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_scenarios_storyline_id'))
        batch_op.drop_index(batch_op.f('ix_scenarios_setting_id'))

    op.drop_table('scenarios')
    with op.batch_alter_table('graph_type_definitions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_graph_type_definitions_storyline_id'))

    op.drop_table('graph_type_definitions')
    with op.batch_alter_table('context_documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_context_documents_storyline_id'))

    op.drop_table('context_documents')
    with op.batch_alter_table('characters', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_characters_storyline_id'))

    op.drop_table('characters')
    op.drop_table('storylines')
    op.drop_table('app_settings')
    # ### end Alembic commands ###
